name: Run Minecraft Bot

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'  # Update to 14.x or higher

      - name: Install dependencies
        run: npm install

      - name: Run Minecraft Bot
        run: |
          nohup node bot.js &
